/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary-container': '#a5d8ff',
        'surface-dim': '#d9dadd',
        'secondary-container': '#f5e1ae',
        background: '#f9f9fc',
        'secondary-fixed': '#f5e1ae',
        tertiary: '#7d5718',
        'primary-fixed': '#c9e6ff',
        'surface-container-high': '#e7e8eb',
        'surface-variant': '#e1e2e5',
        'on-secondary-fixed-variant': '#534520',
        'surface-container-low': '#f3f3f6',
        'on-tertiary-fixed-variant': '#624000',
        'inverse-primary': '#9accf3',
        'tertiary-fixed': '#ffddb2',
        'on-secondary': '#ffffff',
        'tertiary-fixed-dim': '#f1be75',
        'on-error-container': '#93000a',
        'tertiary-container': '#fdc97f',
        'secondary-fixed-dim': '#d8c594',
        'surface-container': '#edeef1',
        'on-tertiary': '#ffffff',
        'on-secondary-fixed': '#241a00',
        'on-primary-container': '#285f80',
        'outline-variant': '#c1c7ce',
        'error-container': '#ffdad6',
        'on-background': '#191c1e',
        'surface-container-lowest': '#ffffff',
        'surface-bright': '#f9f9fc',
        'on-primary-fixed-variant': '#0c4b6c',
        primary: '#2e6385',
        'inverse-surface': '#2e3133',
        surface: '#f9f9fc',
        error: '#ba1a1a',
        'surface-container-highest': '#e1e2e5',
        'on-secondary-container': '#72633a',
        'primary-fixed-dim': '#9accf3',
        'on-surface-variant': '#41484d',
        'on-tertiary-container': '#785313',
        'on-error': '#ffffff',
        secondary: '#6b5d35',
        outline: '#71787e',
        'inverse-on-surface': '#f0f0f4',
        'surface-tint': '#2e6385',
        'on-surface': '#191c1e',
        'on-tertiary-fixed': '#291800',
        'on-primary-fixed': '#001e2f',
        'on-primary': '#ffffff',
        ivory: '#FFFDF9',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        gutter: '16px',
        'container-margin': '24px',
        'section-gap': '40px',
        unit: '8px',
      },
      fontFamily: {
        'scripture-text': ['Playfair Display', 'serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'headline-lg': ['Playfair Display', 'serif'],
        'label-md': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Playfair Display', 'serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'display-lg': ['Playfair Display', 'serif'],
        serif: ['Playfair Display', 'serif'],
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'scripture-text': ['22px', { lineHeight: '34px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        breathe: {
          '0%, 100%': { transform: 'scale(1)', boxShadow: '0 0 20px rgba(186, 26, 26, 0.2)' },
          '50%': { transform: 'scale(1.05)', boxShadow: '0 0 40px rgba(186, 26, 26, 0.4)' },
        },
        progress: {
          '0%': { strokeDasharray: '0 100' },
        },
      },
      animation: {
        'fade-in': 'fadeIn 0.6s ease-out',
        breathe: 'breathe 8s infinite ease-in-out',
        progress: 'progress 1s ease-out forwards',
      },
    },
  },
  plugins: [],
};
